apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: audit-logging-fetch-and-log-job
  namespace: teamcrm
  labels:
    team: teamcrm
spec:
  schedule: "0 1 * * *"  # This will run the job every day at 01:00 AM UTC (02:00 AM CET)
  image: "{{ image }}" # Will use cgr.dev/chainguard/curl:latest via Dockerfile-job
  accessPolicy:
    outbound:
      rules:
        - application: sf-audit-logging
  command:
    - curl
    - http://sf-audit-logging/internal/fetchAndLog
  restartPolicy: Never