apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sf-audit-logging
  namespace: platforce
  labels:
    team: platforce
spec:
  image: "{{ image }}"
  port: 8080
  replicas:
    min: 1
    max: 1
  liveness:
    path: /internal/isAlive
  readiness:
    path: /internal/isReady
  prometheus:
    enabled: true
    path: /internal/metrics
  observability:
    logging:
      destinations:
        - id: loki
  resources:
    limits:
      memory: 2Gi
    requests:
      cpu: 20m
      memory: 384Mi
  gcp:
    sqlInstances:
      - type: POSTGRES_16
        tier: db-f1-micro
        databases:
          - name: sf-audit-logging-prod
  ingresses:
    - "https://sf-audit-logging.intern.nav.no"
  accessPolicy:
    inbound:
      rules:
        - application: audit-logging-fetch-and-log-job
        - application: audit-logging-fetch-and-log-job-for-cases
    outbound:
      external:
        - host: navdialog.my.salesforce.com
  env:
    - name: CONTEXT
      value: "PROD"
  envFrom:
    - configmap: salesforce-common
    - secret: sf-audit-logging-prod
